title: Mi Sitio Jekyll
description: Ejemplo práctico de Jekyll
author: Tu Nombre
email: tunombre@example.com
baseurl: "" 
url: "https://tuusuario.github.io"

collections:
  proyectos:
    output: true
